export var atributos = {
1: {id: '#bloco1', group: '#Gbloco1', texto: 'Laboratório 3'}, 
2:{id: '#bloco2', group: '#Gbloco2', texto: 'Laboratório 1'},
3: {id: '#bloco3', group: '#Gbloco3', texto: 'Laboratório 2'},
4:{id: '#bloco4', group: '#Gbloco4', texto: 'Almoxarifado'},
5: {id: '#bloco5', group: '#Gbloco5', texto: 'Estufa e Implementos'},
6: {id: '#bloco6', group: '#Gbloco6', texto: 'Centro Vocacional Tecnológico'},
7: {id: '#bloco7', group: '#Gbloco7', texto: 'Cantina'},
8: {id: '#bloco8', group: '#Gbloco8', texto: 'Bloco A'},
9: {id: '#bloco9', group: '#Gbloco9', texto: 'Bloco dos Professores'},
10: {id: '#bloco10', group: '#Gbloco10', texto: 'Restaurante Universitário'},
11: {id: '#bloco11', group: '#Gbloco11', texto: 'Estufa'},
12: {id: '#bloco12', group: '#Gbloco12', texto: 'Hortas'},
13: {id: '#bloco13', group: '#Gbloco13', texto: 'Área Experimental'},
14: {id: '#bloco14', group: '#Gbloco14', texto: 'Área de Tratamento'},
};
