export var atributos = {
    1: {id: '#bloco1', group: '#Gbloco1', id_360:"14-laboratrio-3",
        titulo: 'Laboratório 3', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:", list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }}, 
    2:{id: '#bloco2', group: '#Gbloco2', id_360:"13-laboratrio-1",
        titulo: 'Laboratório 1', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    3: {id: '#bloco3', group: '#Gbloco3', id_360:"1-laboratrio-2",
        titulo: 'Laboratório 2', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    4:{id: '#bloco4', group: '#Gbloco4', id_360:"2-almoxarifado",
        titulo: 'Almoxarifado', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    5: {id: '#bloco5', group: '#Gbloco5', id_360:"0-estufas",
        titulo: 'Estufa e Implementos', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    6: {id: '#bloco6', group: '#Gbloco6', id_360:"6-cvt",
        titulo: 'Centro Vocacional Tecnológico', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    7: {id: '#bloco7', group: '#Gbloco7', id_360:"12-cantina",
        titulo: 'Cantina', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    8: {id: '#bloco8', group: '#Gbloco8', id_360:"9-bloco-a-fora",
        titulo: 'Bloco A', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    9: {id: '#bloco9', group: '#Gbloco9', id_360:"11-bloco-dos-professores-fora",
        titulo: 'Bloco dos Professores', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    10: {id: '#bloco10', group: '#Gbloco10', id_360:"7-ru-fora",
        titulo: 'Restaurante Universitário', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    11: {id: '#bloco11', group: '#Gbloco11', id_360:"0-estufas",
        titulo: 'Estufa', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    12: {id: '#bloco12', group: '#Gbloco12', id_360:"0-estufas",
        titulo: 'Hortas',  descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    13: {id: '#bloco13', group: '#Gbloco13', id_360:"3-rea-experimental-aquicultura-2",
        titulo: 'Área Experimental', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:", list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    14: {id: '#bloco14', group: '#Gbloco14', id_360:"",
        titulo: 'Área de Tratamento', descricao: "Neste bloco é onde ocorre a maioria das aulas. Estão presentes, também:",list_description:{
            1: "Secretaria Acadêmica",
            2: "SAE (Setor de Assuntos Estudantis)",
            3: "Setor de Acessibilidade",
            4: "Biblioteca",
            5: "Cantina",
            6: "Sala de Monitorias",
            7: "Secretaria Geral de Cursos",
            8: "Assessoria",
            9: "Direção do Campus",
            10: "Auditório",
        }},
    };

   